version: '3.8'

services:
  kitchen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitchen_container
    ports:
      - "50052:50052"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - default

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.goose
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["sh", "-c", "sleep 10 && goose -dir=/migrations postgres 'host=db user=${DB_USER:-postgres} password=${DB_PASSWORD:-password} dbname=${DB_NAME:-kitchen} sslmode=disable' up"]
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    driver: bridge
