version: '3.8'

services:
  kitchen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitchen_container
    ports:
      - "50052:50052"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  migrations:
    build:
      context: .
      dockerfile: goose.dockerfile
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "goose", "-dir=/migrations", "postgres", "host=db user=postgres dbname=kitchen password=password sslmode=disable", "up" ]
    depends_on:
      - db

networks:
  default:
    driver: bridge
